### ISSUE TITLE
Why did you rotate images in LoadDICOMImages.m?

### ISSUE THREAD

**Issue by daolamgit** [mwgeurts/dicom_tools#21]
Line 310: single(rot90(permute(images(indices(i), :, :), [2 3 1])));

**Comment by daolamgit** [comment]
Also flip image along X axis? What is the reason?

**Comment by mwgeurts** [comment]
Hi there, I rotate/permute to store the images internally such that the IEC X axis is the first dimension, Z is the second, and Y is the third, in order to use a format that is consistent with what is used in some planning systems (such as Pinnacle and TomoTherapy). I re-orient them back in the Write* functions.

**Comment by daolamgit** [comment]
I figured it out and just rotated && flipped images before I use them. Thanks for your answer.
